default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mysite_development
  username: postgres
  password: 9999
  host: localhost
  port: 5432

test:
  <<: *default
  database: mysite_test
  username: postgres
  password: 9999
  host: localhost
  port: 5432

# production:
#   <<: *default
#   database: mysite_production
#   username: <%= ENV["MYSITE_DATABASE_USERNAME"] %>
#   password: <%= ENV["MYSITE_DATABASE_PASSWORD"] %>
#   host: <%= ENV["DATABASE_HOST"] %>
#   port: <%= ENV["DATABASE_PORT"] %>
